version: '3'

services:

  frontend:
    container_name: frontend
    image: frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

  backend:
    container_name: backend
    image: backend
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app

  database:
    container_name: database
    image: mysql
    ports:
      - "3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: cspeed
      MYSQL_USER: cspeed
      MYSQL_PASSWORD: cspeed
