apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: muhammedriaz/cspeed-frontend
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: http://backend:4000
          imagePullPolicy: Always
